version: '3'

services:
  # Database
  db:
    image: mysql:8.0.26
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: maher
      MYSQL_PASSWORD: maher
    ports:
      - "6033:3306"
    networks:
      - backend
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

networks:
  backend:
volumes:
  db_data: